<a href="https://colab.research.google.com/github/koh-hongQ/Understanding_ML_with_Math/blob/main/MLwithmath_pandas_250322.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **수학으로 이해하는 기계학습**


---
*   수학과 22학번 고홍규
*   과제 250322
*   판다스 기초 1

In [3]:
import pandas as pd

In [4]:
#구글 드라이브 연결
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
!ls "/content/drive/My Drive/Colab Notebooks/2025MLwithmath/titanic/train.csv"

'/content/drive/My Drive/Colab Notebooks/2025MLwithmath/titanic/train.csv'

In [6]:
df=pd.read_csv("drive/My Drive/Colab Notebooks/2025MLwithmath/titanic/train.csv")

In [7]:
df.to_csv("drive/My Drive/Colab Notebooks/2025MLwithmath/titanic/train2.csv")

In [8]:
df.head() #디폴트로 5개 출력

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
df.shape # 데이터 행 열 개수 출력. ()괄호 안붙임 주의

(891, 12)

In [10]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [11]:
df.info() #열 마다 자료의 타입이 object=글자, int/float=숫자

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [12]:
df.describe() #자료의 열마다 평균, 표준편차 등

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [13]:
df.corr(numeric_only=True) #자료의 열마다 상관관계

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651
Parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225
Fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000

# 데이터프레임과 시리즈

In [14]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [15]:
df['Fare'] #특정 열의 자료 다 출력

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [16]:
df.Fare #특정 열의 자료 다 출력

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [18]:
df[['Pclass','Fare']] #두개 이상의 열 출력하려면 대괄호 두개 주의

     Pclass     Fare
0         3   7.2500
1         1  71.2833
2         3   7.9250
3         1  53.1000
4         3   8.0500
..      ...      ...
886       2  13.0000
887       1  30.0000
888       3  23.4500
889       1  30.0000
890       3   7.7500

[891 rows x 2 columns]

In [19]:
df['Pclass'].value_counts() #특정 열에서, 특정 겹치는 자료값이 몇개씩인지 출력

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

# 결측치

In [20]:
df.isnull().sum() #열마다 결측치의 개수 각각 출력

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [21]:
df['Age'].mean() #평균

np.float64(29.69911764705882)

In [22]:
df['Age']=df['Age'].fillna(df['Age'].mean()) #결측치를 평균으로 채움

In [24]:
df=df.drop('Cabin',axis=1) #Cabin 열 삭제. axis는 행=0, 열=1인데 그중 뭘할지정하는거

In [25]:
df.isnull().sum() #열마다 결측치의 개수 각각 출력

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

In [26]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [28]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
#결측치를 df['Embarked'].mode()[0] = Embarked의최빈값인S  로 채움

In [29]:
df.isnull().sum() #열마다 결측치의 개수 각각 출력

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [30]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

# 범주형 데이터 처리

In [31]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [36]:
#원핫인코딩
df_sex=pd.get_dummies(df['Sex'])
#Sex열을 2개의 열로 분해(Sex자료는 값이 female아니면male둘뿐이라 그 두개의열)
df_sex.head()

   female   male
0   False   True
1    True  False
2    True  False
3    True  False
4   False   True

from matplotlib import pyplot as plt
import seaborn as sns
_df_0.groupby('female').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_1.groupby('male').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['male'].value_counts()
    for x_label, grp in _df_2.groupby('female')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('female')
_ = plt.ylabel('male')

In [37]:
df_encoding=pd.concat([df,df_sex],axis=1)
#df_encoding이라는 곳에 df와df_sex자료 합침
df_encoding.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,female,male
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,True,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,True,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,True,False
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,False,True

In [38]:
df_encoding=df_encoding.drop('Sex',axis=1)
#Sex열 삭제
df_encoding.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Embarked,female,male
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,S,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C,True,False
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,S,True,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,S,True,False
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,S,False,True

In [41]:
#원핫인코딩
df_embarked=pd.get_dummies(df['Embarked'])
#embarked열을 3개의 열로 분해(embarked자료는 값이 C,Q,S뿐이라 그 3개의열)
df_embarked.head()

       C      Q      S
0  False  False   True
1   True  False  False
2  False  False   True
3  False  False   True
4  False  False   True

In [42]:
df_encoding=pd.concat([df,df_embarked],axis=1)
#df_encoding이라는 곳에 df와df_embarked자료 합침
df_encoding=df_encoding.drop('Embarked',axis=1)
df_encoding.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,C,Q,S
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,False,False,True

In [43]:
del df_sex, df_embarked

In [44]:
df_encoding['Ticket'].value_counts()

Ticket
347082              7
1601                7
CA. 2343            7
3101295             6
CA 2144             6
                   ..
PC 17590            1
17463               1
330877              1
373450              1
STON/O2. 3101282    1
Name: count, Length: 681, dtype: int64

In [46]:
df_encoding['Ticket'].unique() #모든 Ticket의 변수들 다 출력

array(['A/5 21171', 'PC 17599', 'STON/O2. 3101282', '113803', '373450',
       '330877', '17463', '349909', '347742', '237736', 'PP 9549',
       '113783', 'A/5. 2151', '347082', '350406', '248706', '382652',
       '244373', '345763', '2649', '239865', '248698', '330923', '113788',
       '347077', '2631', '19950', '330959', '349216', 'PC 17601',
       'PC 17569', '335677', 'C.A. 24579', 'PC 17604', '113789', '2677',
       'A./5. 2152', '345764', '2651', '7546', '11668', '349253',
       'SC/Paris 2123', '330958', 'S.C./A.4. 23567', '370371', '14311',
       '2662', '349237', '3101295', 'A/4. 39886', 'PC 17572', '2926',
       '113509', '19947', 'C.A. 31026', '2697', 'C.A. 34651', 'CA 2144',
       '2669', '113572', '36973', '347088', 'PC 17605', '2661',
       'C.A. 29395', 'S.P. 3464', '3101281', '315151', 'C.A. 33111',
       'S.O.C. 14879', '2680', '1601', '348123', '349208', '374746',
       '248738', '364516', '345767', '345779', '330932', '113059',
       'SO/C 14885', '3101278', 'W./C. 6608', 'SOTON/OQ 392086', '343275',
       '343276', '347466', 'W.E.P. 5734', 'C.A. 2315', '364500', '374910',
       'PC 17754', 'PC 17759', '231919', '244367', '349245', '349215',
       '35281', '7540', '3101276', '349207', '343120', '312991', '349249',
       '371110', '110465', '2665', '324669', '4136', '2627',
       'STON/O 2. 3101294', '370369', 'PC 17558', 'A4. 54510', '27267',
       '370372', 'C 17369', '2668', '347061', '349241',
       'SOTON/O.Q. 3101307', 'A/5. 3337', '228414', 'C.A. 29178',
       'SC/PARIS 2133', '11752', '7534', 'PC 17593', '2678', '347081',
       'STON/O2. 3101279', '365222', '231945', 'C.A. 33112', '350043',
       '230080', '244310', 'S.O.P. 1166', '113776', 'A.5. 11206',
       'A/5. 851', 'Fa 265302', 'PC 17597', '35851', 'SOTON/OQ 392090',
       '315037', 'CA. 2343', '371362', 'C.A. 33595', '347068', '315093',
       '363291', '113505', 'PC 17318', '111240', 'STON/O 2. 3101280',
       '17764', '350404', '4133', 'PC 17595', '250653', 'LINE',
       'SC/PARIS 2131', '230136', '315153', '113767', '370365', '111428',
       '364849', '349247', '234604', '28424', '350046', 'PC 17610',
       '368703', '4579', '370370', '248747', '345770', '3101264', '2628',
       'A/5 3540', '347054', '2699', '367231', '112277',
       'SOTON/O.Q. 3101311', 'F.C.C. 13528', 'A/5 21174', '250646',
       '367229', '35273', 'STON/O2. 3101283', '243847', '11813',
       'W/C 14208', 'SOTON/OQ 392089', '220367', '21440', '349234',
       '19943', 'PP 4348', 'SW/PP 751', 'A/5 21173', '236171', '347067',
       '237442', 'C.A. 29566', 'W./C. 6609', '26707', 'C.A. 31921',
       '28665', 'SCO/W 1585', '367230', 'W./C. 14263',
       'STON/O 2. 3101275', '2694', '19928', '347071', '250649', '11751',
       '244252', '362316', '113514', 'A/5. 3336', '370129', '2650',
       'PC 17585', '110152', 'PC 17755', '230433', '384461', '110413',
       '112059', '382649', 'C.A. 17248', '347083', 'PC 17582', 'PC 17760',
       '113798', '250644', 'PC 17596', '370375', '13502', '347073',
       '239853', 'C.A. 2673', '336439', '347464', '345778', 'A/5. 10482',
       '113056', '349239', '345774', '349206', '237798', '370373',
       '19877', '11967', 'SC/Paris 2163', '349236', '349233', 'PC 17612',
       '2693', '113781', '19988', '9234', '367226', '226593', 'A/5 2466',
       '17421', 'PC 17758', 'P/PP 3381', 'PC 17485', '11767', 'PC 17608',
       '250651', '349243', 'F.C.C. 13529', '347470', '29011', '36928',
       '16966', 'A/5 21172', '349219', '234818', '345364', '28551',
       '111361', '113043', 'PC 17611', '349225', '7598', '113784',
       '248740', '244361', '229236', '248733', '31418', '386525',
       'C.A. 37671', '315088', '7267', '113510', '2695', '2647', '345783',
       '237671', '330931', '330980', 'SC/PARIS 2167', '2691',
       'SOTON/O.Q. 3101310', 'C 7076', '110813', '2626', '14313',
       'PC 17477', '11765', '3101267', '323951', 'C 7077', '113503',
       '2648', '347069', 'PC 17757', '2653', 'STON/O 2. 3101293',
       '349227', '27849', '367655', 'SC 1748', '113760', '350034',
       '3101277', '350052', '350407', '28403', '244278', '240929',
       'STON/O 2. 3101289', '341826', '4137', '315096', '28664', '347064',
       '29106', '312992', '349222', '394140', 'STON/O 2. 3101269',
       '343095', '28220', '250652', '28228', '345773', '349254',
       'A/5. 13032', '315082', '347080', 'A/4. 34244', '2003', '250655',
       '364851', 'SOTON/O.Q. 392078', '110564', '376564', 'SC/AH 3085',
       'STON/O 2. 3101274', '13507', 'C.A. 18723', '345769', '347076',
       '230434', '65306', '33638', '113794', '2666', '113786', '65303',
       '113051', '17453', 'A/5 2817', '349240', '13509', '17464',
       'F.C.C. 13531', '371060', '19952', '364506', '111320', '234360',
       'A/S 2816', 'SOTON/O.Q. 3101306', '113792', '36209', '323592',
       '315089', 'SC/AH Basle 541', '7553', '31027', '3460', '350060',
       '3101298', '239854', 'A/5 3594', '4134', '11771', 'A.5. 18509',
       '65304', 'SOTON/OQ 3101317', '113787', 'PC 17609', 'A/4 45380',
       '36947', 'C.A. 6212', '350035', '315086', '364846', '330909',
       '4135', '26360', '111427', 'C 4001', '382651', 'SOTON/OQ 3101316',
       'PC 17473', 'PC 17603', '349209', '36967', 'C.A. 34260', '226875',
       '349242', '12749', '349252', '2624', '2700', '367232',
       'W./C. 14258', 'PC 17483', '3101296', '29104', '2641', '2690',
       '315084', '113050', 'PC 17761', '364498', '13568', 'WE/P 5735',
       '2908', '693', 'SC/PARIS 2146', '244358', '330979', '2620',
       '347085', '113807', '11755', '345572', '372622', '349251',
       '218629', 'SOTON/OQ 392082', 'SOTON/O.Q. 392087', 'A/4 48871',
       '349205', '2686', '350417', 'S.W./PP 752', '11769', 'PC 17474',
       '14312', 'A/4. 20589', '358585', '243880', '2689',
       'STON/O 2. 3101286', '237789', '13049', '3411', '237565', '13567',
       '14973', 'A./5. 3235', 'STON/O 2. 3101273', 'A/5 3902', '364848',
       'SC/AH 29037', '248727', '2664', '349214', '113796', '364511',
       '111426', '349910', '349246', '113804', 'SOTON/O.Q. 3101305',
       '370377', '364512', '220845', '31028', '2659', '11753', '350029',
       '54636', '36963', '219533', '349224', '334912', '27042', '347743',
       '13214', '112052', '237668', 'STON/O 2. 3101292', '350050',
       '349231', '13213', 'S.O./P.P. 751', 'CA. 2314', '349221', '8475',
       '330919', '365226', '349223', '29751', '2623', '5727', '349210',
       'STON/O 2. 3101285', '234686', '312993', 'A/5 3536', '19996',
       '29750', 'F.C. 12750', 'C.A. 24580', '244270', '239856', '349912',
       '342826', '4138', '330935', '6563', '349228', '350036', '24160',
       '17474', '349256', '2672', '113800', '248731', '363592', '35852',
       '348121', 'PC 17475', '36864', '350025', '223596', 'PC 17476',
       'PC 17482', '113028', '7545', '250647', '348124', '34218', '36568',
       '347062', '350048', '12233', '250643', '113806', '315094', '36866',
       '236853', 'STON/O2. 3101271', '239855', '28425', '233639',
       '349201', '349218', '16988', '376566', 'STON/O 2. 3101288',
       '250648', '113773', '335097', '29103', '392096', '345780',
       '349204', '350042', '29108', '363294', 'SOTON/O2 3101272', '2663',
       '347074', '112379', '364850', '8471', '345781', '350047',
       'S.O./P.P. 3', '2674', '29105', '347078', '383121', '36865',
       '2687', '113501', 'W./C. 6607', 'SOTON/O.Q. 3101312', '374887',
       '3101265', '12460', 'PC 17600', '349203', '28213', '17465',
       '349244', '2685', '2625', '347089', '347063', '112050', '347087',
       '248723', '3474', '28206', '364499', '112058', 'STON/O2. 3101290',
       'S.C./PARIS 2079', 'C 7075', '315098', '19972', '368323', '367228',
       '2671', '347468', '2223', 'PC 17756', '315097', '392092', '11774',
       'SOTON/O2 3101287', '2683', '315090', 'C.A. 5547', '349213',
       '347060', 'PC 17592', '392091', '113055', '2629', '350026',
       '28134', '17466', '233866', '236852', 'SC/PARIS 2149', 'PC 17590',
       '345777', '349248', '695', '345765', '2667', '349212', '349217',
       '349257', '7552', 'C.A./SOTON 34068', 'SOTON/OQ 392076', '211536',
       '112053', '111369', '370376'], dtype=object)

In [48]:
df_encoding.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,C,Q,S
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,False,False,True

In [49]:
#행 삭제
df_encoding = df.drop('PassengerId', axis=1)
df_encoding = df_encoding.drop('Name', axis=1)
df_encoding = df_encoding.drop('Ticket', axis=1)

In [50]:
#바뀐 데이터 저장
df_encoding.to_csv('drive/My Drive/Colab Notebooks/2025MLwithmath/titanic/train_encoding.csv')

# 과제

1.   결측치 처리(Age,Cabin,Embarked)
2.   범주형데이터 처리(원핫인코딩:Sex, Embarked)
3. PassengerId, Name, Ticket 행 삭제

In [51]:
#데이터 불러오기
train=pd.read_csv("drive/My Drive/Colab Notebooks/2025MLwithmath/titanic/train.csv")

In [52]:
#전처리 함수
def preprocessing(df):
  df['Age']=df['Age'].fillna(df['Age'].mean())
  df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
  df['Cabin'] = df['Cabin'].fillna(df['Cabin'].mode()[0])
  #원핫인코딩
  df_embarked=pd.get_dummies(df['Embarked'])
  df=pd.concat([df,df_embarked],axis=1)
  df=df.drop('Embarked',axis=1)
  df_sex=pd.get_dummies(df['Sex'])
  df=pd.concat([df,df_sex],axis=1)
  df=df.drop('Sex',axis=1)

  df = df.drop('PassengerId', axis=1)
  df = df.drop('Name', axis=1)
  df = df.drop('Ticket', axis=1)
  return df

In [53]:
train_pre = preprocessing(train)
train_pre.head()

,Survived,Pclass,Age,SibSp,Parch,Fare,Cabin,C,Q,S,female,male
0,0,3,22.0,1,0,7.2500,B96 B98,False,False,True,False,True
1,1,1,38.0,1,0,71.2833,C85,True,False,False,True,False
2,1,3,26.0,0,0,7.9250,B96 B98,False,False,True,True,False
3,1,1,35.0,1,0,53.1000,C123,False,False,True,True,False
4,0,3,35.0,0,0,8.0500,B96 B98,False,False,True,False,True